use miette::Diagnostic;
use tracing::info;

use super::initialize_state;
use crate::{
    app_config, config,
    integrations::{ApiRequestError, CreateReleaseInput, git, http::handle_response},
    state,
    state::RunType,
};

pub(crate) async fn create_release(
    name: &str,
    tag_name: &str,
    body: &str,
    prerelease: bool,
    gitea_state: RunType<state::Gitea>,
    gitea_config: &config::Gitea,
) -> Result<state::Gitea, Error> {
    // Dry-run: use commit SHA for display so snapshot [COMMIT] placeholders still match.
    if let RunType::DryRun(state) = gitea_state {
        let display_target = git::get_head_commit_sha().ok();
        let dry_run_release = CreateReleaseInput::new(
            tag_name,
            name,
            body,
            prerelease,
            false,
            display_target.as_deref(),
        );
        gitea_release_dry_run(name, gitea_config, &dry_run_release);
        return Ok(state);
    }

    let RunType::Real(gitea_state) = gitea_state else {
        unreachable!("non-dry-run branch already handled above")
    };
    let (token, client) = initialize_state(&gitea_config.host, gitea_state)?;

    // For the actual API call, prefer the branch short name over a raw commit SHA.
    // Forgejo resolves branch names reliably via `git rev-parse`, whereas some Forgejo
    // versions (including Codeberg's) fail to look up a bare commit SHA when creating
    // the repository's very first tag.
    let api_target = git::get_gitea_target_commitish();
    let api_release = CreateReleaseInput::new(
        tag_name,
        name,
        body,
        prerelease,
        false,
        api_target.as_deref(),
    );

    let resp = client
        .post(gitea_config.get_releases_url())
        .header("Authorization", format!("Bearer {token}"))
        .json(&api_release)
        .send()
        .await;
    handle_response(
        resp,
        gitea_config.host.clone(),
        "creating a release".to_string(),
    )
    .await?;

    Ok(state::Gitea::Initialized { token, client })
}

fn gitea_release_dry_run(name: &str, config: &config::Gitea, gitea_release: &CreateReleaseInput) {
    let release_type = if gitea_release.prerelease {
        "prerelease"
    } else {
        "release"
    };
    let body = gitea_release.body.as_ref().map_or_else(
        || String::from("(will be auto-generated by Gitea)"),
        |body| format!("body:\n{body}"),
    );
    let target = gitea_release
        .target_commitish
        .map_or_else(String::new, |sha| format!(" at commit {sha}"));
    info!(
        "Would create a {release_type} on Gitea [{host}] with name {name} and tag {tag}{target} and {body}",
        tag = gitea_release.tag_name,
        host = config.host
    );
}

#[derive(Debug, Diagnostic, thiserror::Error)]
pub(crate) enum Error {
    #[error(transparent)]
    #[diagnostic(transparent)]
    AppConfig(#[from] app_config::Error),
    #[error(transparent)]
    #[diagnostic(transparent)]
    ApiRequest(#[from] ApiRequestError),
}
