name: Publish crates

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:

permissions: {}

jobs:
  publish-crates:
    if:  (github.head_ref == 'knope/release' && github.event.pull_request.merged == true) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: "crates.io"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      - uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1.0.5
        id: auth
      - name: Install cargo-release
        run: cargo install cargo-release
      - run: cargo release publish --workspace --execute --no-confirm
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
