name: Run Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group:

permissions: {}

jobs:
  checks:
    name: Run Checks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      
      - name: Install nightly toolchain (for formatting)
        if: matrix.os == 'ubuntu-latest'
        run: rustup toolchain install nightly --component rustfmt

      - uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          install: ${{ matrix.os == 'ubuntu-latest' }}

      - uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6.0.0
        if: matrix.os == 'ubuntu-latest'
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-docs-deps-${{ hashFiles('docs/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docs-deps-

      - name: Install docs dependencies
        if: matrix.os == 'ubuntu-latest'
        run: mise run install-docs-dependencies

      - name: Run CI
        if: matrix.os == 'ubuntu-latest'
        run: mise run ci

      - name: Run tests only
        if: matrix.os == 'windows-latest'
        run: mise run --skip-tools test

  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - run: npm install -g mdx2vast # Adds MDX support for Vale
      - uses: vale-cli/vale-action@0135b9fe2b3107365569cc3142b9a1c85221ea2f
        with:
          files: '["docs", "README.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]'
