name: Run Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group:

permissions: {}

jobs:
  checks:
    name: Run Checks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      
      - name: Install nightly toolchain (for formatting)
        if: matrix.os == 'ubuntu-latest'
        run: rustup toolchain install nightly --component rustfmt

      - uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          install: ${{ matrix.os == 'ubuntu-latest' }}

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: matrix.os == 'ubuntu-latest'
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-docs-deps-${{ hashFiles('docs/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docs-deps-

      - name: Install docs dependencies
        if: matrix.os == 'ubuntu-latest'
        run: mise run install-docs-dependencies

      - name: Run CI
        if: matrix.os == 'ubuntu-latest'
        run: mise run ci

      - name: Run tests only
        if: matrix.os == 'windows-latest'
        run: mise run --skip-tools test

  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: npm install -g mdx2vast # Adds MDX support for Vale
      - uses: vale-cli/vale-action@0135b9fe2b3107365569cc3142b9a1c85221ea2f
        with:
          files: '["docs", "README.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]'
