name: Run Checks
on:
  push:
    branches:
      - main
  pull_request: {}
  merge_group:

permissions: {}

jobs:
  checks:
    name: Run Checks
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@150fca883cd4034361b621bd4e6a9d34e5143606 # v1.15.4
      
      - name: Install nightly toolchain (for formatting)
        if: matrix.os == 'ubuntu-latest'
        run: rustup toolchain install nightly --component rustfmt

      - uses: jdx/mise-action@c1ecc8f748cd28cdeabf76dab3cccde4ce692fe4 # v4.0.0

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        if: matrix.os == 'ubuntu-latest'
        with:
          path: docs/node_modules
          key: ${{ runner.os }}-docs-deps-${{ hashFiles('docs/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docs-deps-

      - name: Install docs dependencies
        if: matrix.os == 'ubuntu-latest'
        run: mise run install-docs-dependencies

      - name: Run CI
        if: matrix.os == 'ubuntu-latest'
        run: mise run ci

      - name: Run tests only
        if: matrix.os == 'windows-latest'
        run: mise run test

  vale:
    name: Vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: npm install -g mdx2vast # Adds MDX support for Vale
      - uses: vale-cli/vale-action@0135b9fe2b3107365569cc3142b9a1c85221ea2f
        with:
          files: '["docs", "README.md", "CODE_OF_CONDUCT.md", "CONTRIBUTING.md"]'
